-- Compute, for every country, the value 
-- of economic exchange, i.e., the difference 
-- between the numberof items from suppliers in
-- that country sold to customers in other countries
-- and the number of items bought by local customers from
-- foreign suppliers in 1994 (lshipdate).