-- Find  how  many  distinct  customers  
-- have  at  least  one  order  supplied  
-- exclusively  by  suppliers  from AMERICA.

-- ima figure this out later

-- SELECT COUNT(DISTINCT c_custkey) 
-- FROM customer c, supplier s
-- WHERE 1 < 
--     (SELECT COUNT(DISTINCT o_orderkey)
--     FROM orders, supplier supp, lineitem
--     WHERE o_orderkey = l_orderkey 
--         AND l_suppkey = supp.s_suppkey 
--         AND s.s_nationkey IN (
--         SELECT n_nationkey 
--         FROM nation 
--         WHERE n_regionkey = 
--             (SELECT r_regionkey 
--             FROM region reg
--             WHERE reg.r_name = 'AMERICA')
--         )
--     )