-- For any two regions, find the gross discounted revenue 
-- (lextendedprice*(1-ldiscount)) derivedfrom  line  items
--  in  which  parts  are  shipped  from  a  supplier  in  the 
-- first  region  to  a  customer  in  the second region in 1996 and 1997.
-- List the supplier region, the customer region, the year 
-- (lshipdate),and the revenue from shipments that took place in that year.