-- Print the name of the parts supplied by suppliers from
-- UNITED STATES that have total value in the top 1% total
-- values across all the supplied parts.  The total value is 
-- pssupplycost*psavailqty.  Hint:Use the LIMIT keyword.