--List the maximum total price  
--of an order between any two
-- regions,  i.e.,  the suppliers
-- are from one region and the 
--customers are from the other
-- region.

-- SELECT r_name, MAX(o_totalprice)
-- FROM orders, region, nation, lineitem, supplier
-- WHERE o_custkey = c_custkey 
--     AND c_nationkey = n_nationkey 
--     AND 